### ISSUE TITLE
[BUG] Numpy array slicing produces scalar.

### ISSUE THREAD

**Issue by kwagyeman** [v923z/micropython-ulab#696]
I think I found a bug with slicing arrays:

```
from ulab import numpy as np

# Example bounding_boxes array
bounding_boxes = np.array([
    [0, 0, 0, 0, 0, 0.1, 0.2, 0.7, 0.3],
    [0, 0, 0, 0, 0, 0.3, 0.4, 0.3, 0.1],
    [0, 0, 0, 0, 0, 0.6, 0.1, 0.3, 0.2]
])

TINY_YOLO_V2_CLASSES = 5

class_scores_raw = bounding_boxes[:, TINY_YOLO_V2_CLASSES:]

def softmax(x):
    max_x = np.max(x, axis=1)
    e_x = np.exp(x - max_x.reshape((x.shape[0], 1)))
    sum_e_x = np.sum(e_x, axis=1)
    return e_x / sum_e_x.reshape((x.shape[0], 1))

bb_classes = np.argmax(softmax(class_scores_raw), axis=1)

print(bb_classes)
```

Works and outputs `array([2, 1, 0], dtype=int16)`.

Now if I modify the array to be:

```
from ulab import numpy as np

# Example bounding_boxes array
bounding_boxes = np.array([
    [0, 0, 0, 0, 0, 0.1],
])

TINY_YOLO_V2_CLASSES = 5

class_scores_raw = bounding_boxes[:, TINY_YOLO_V2_CLASSES:]

def softmax(x):
    max_x = np.max(x, axis=1)
    e_x = np.exp(x - max_x.reshape((x.shape[0], 1)))
    sum_e_x = np.sum(e_x, axis=1)
    return e_x / sum_e_x.reshape((x.shape[0], 1))

bb_classes = np.argmax(softmax(class_scores_raw), axis=1)

print(bb_classes)
```

You get:

```
Traceback (most recent call last):
  File "<stdin>", line 18, in <module>
  File "<stdin>", line 14, in softmax
AttributeError: 'float' object has no attribute 'reshape'
```

This is because `bounding_boxes[:, TINY_YOLO_V2_CLASSES:]` produced a float in this case instead of a numpy array with size 1x1.

I think this is a bug? As slices, even if they produce an array with one value, should still be numpy arrays.

**Comment by kwagyeman** [comment]
Yeah, actually, it's not:

```bounding_boxes[:, TINY_YOLO_V2_CLASSES:]```

This produces: `array([[0.1]], dtype=float32)`

**Comment by kwagyeman** [comment]
Okay, actually, the issue is the lack of keepdims=True.
